SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';


SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;


SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON E.ID_CLIENTE = T.ID_CLIENTE;