UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;


-- DELETE
INSERT INTO CLIENTE VALUES(NULL, 'XXX', 'M', NULL, 'XXX');

SELECT * FROM CLIENTE WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;